<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Api\" />
    <Folder Include="Application\Abstractions\" />
    <Folder Include="Application\DTOs\" />
    <Folder Include="Application\Services\" />
    <Folder Include="Domain\Messages\" />
    <Folder Include="Realtime\Events\" />
    <Folder Include="Realtime\Protocol\Events\" />
    <Folder Include="Realtime\Protocol\Responses\" />
  </ItemGroup>

</Project>
