// <auto-generated />
using System;
using Communicator.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Communicator.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Communicator.Server.Domain.Entities.GroupChats.GcIcon", b =>
                {
                    b.Property<Guid>("GroupChatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupChatId");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("GcIcons");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.GroupChats.GcMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupChatId")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.HasIndex("GroupChatId", "MessageId");

                    b.ToTable("GcMessages");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.GroupChats.GcVoiceCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupChatId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupChatId");

                    b.ToTable("GcVoiceCalls");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.GroupChats.GcVoiceCallParticipant", b =>
                {
                    b.Property<Guid>("GcVoiceCallId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("GcVoiceCallId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GcVoiceCallParticipants");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.GroupChats.GroupChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GroupChats");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.GroupChats.GroupChatMember", b =>
                {
                    b.Property<Guid>("GroupChatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupChatId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupChatMembers");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Media.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("Media");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Messages.DmMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("DmMessages");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CipherText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeSent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("TimeSent");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Messages.MessageAttachment", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("MessageAttachments");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Messages.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactionEm")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeAdded")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("MessageId", "TimeAdded");

                    b.HasIndex("MessageId", "UserId", "ReactionEm")
                        .IsUnique();

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Users.ProfilePicture", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("ProfilePictures");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.GroupChats.GcIcon", b =>
                {
                    b.HasOne("Communicator.Server.Domain.Entities.GroupChats.GroupChat", "GroupChat")
                        .WithOne("Icon")
                        .HasForeignKey("Communicator.Server.Domain.Entities.GroupChats.GcIcon", "GroupChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Communicator.Server.Domain.Entities.Media.Media", "Media")
                        .WithOne("GroupChatIcon")
                        .HasForeignKey("Communicator.Server.Domain.Entities.GroupChats.GcIcon", "MediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupChat");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.GroupChats.GcMessage", b =>
                {
                    b.HasOne("Communicator.Server.Domain.Entities.GroupChats.GroupChat", "GroupChat")
                        .WithMany("Messages")
                        .HasForeignKey("GroupChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Communicator.Server.Domain.Entities.Messages.Message", "Message")
                        .WithOne("GroupChatMessage")
                        .HasForeignKey("Communicator.Server.Domain.Entities.GroupChats.GcMessage", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupChat");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.GroupChats.GcVoiceCall", b =>
                {
                    b.HasOne("Communicator.Server.Domain.Entities.GroupChats.GroupChat", "GroupChat")
                        .WithMany("VoiceCalls")
                        .HasForeignKey("GroupChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupChat");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.GroupChats.GcVoiceCallParticipant", b =>
                {
                    b.HasOne("Communicator.Server.Domain.Entities.GroupChats.GcVoiceCall", "VoiceCall")
                        .WithMany("Participants")
                        .HasForeignKey("GcVoiceCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Communicator.Server.Domain.Entities.Users.User", "User")
                        .WithMany("VoiceCalls")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VoiceCall");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.GroupChats.GroupChatMember", b =>
                {
                    b.HasOne("Communicator.Server.Domain.Entities.GroupChats.GroupChat", "GroupChat")
                        .WithMany("Members")
                        .HasForeignKey("GroupChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Communicator.Server.Domain.Entities.Users.User", "User")
                        .WithMany("GroupChats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupChat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Media.Media", b =>
                {
                    b.HasOne("Communicator.Server.Domain.Entities.Users.User", "Owner")
                        .WithMany("OwnedMedia")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Messages.DmMessage", b =>
                {
                    b.HasOne("Communicator.Server.Domain.Entities.Messages.Message", "Message")
                        .WithOne("DirectMessage")
                        .HasForeignKey("Communicator.Server.Domain.Entities.Messages.DmMessage", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Communicator.Server.Domain.Entities.Users.User", "Receiver")
                        .WithMany("ReceivedDirectMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Messages.Message", b =>
                {
                    b.HasOne("Communicator.Server.Domain.Entities.Users.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Messages.MessageAttachment", b =>
                {
                    b.HasOne("Communicator.Server.Domain.Entities.Media.Media", "Media")
                        .WithMany("MessageAttachments")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Communicator.Server.Domain.Entities.Messages.Message", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Messages.Reaction", b =>
                {
                    b.HasOne("Communicator.Server.Domain.Entities.Messages.Message", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Communicator.Server.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Users.ProfilePicture", b =>
                {
                    b.HasOne("Communicator.Server.Domain.Entities.Media.Media", "Media")
                        .WithOne("ProfilePicture")
                        .HasForeignKey("Communicator.Server.Domain.Entities.Users.ProfilePicture", "MediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Communicator.Server.Domain.Entities.Users.User", "User")
                        .WithOne("ProfilePicture")
                        .HasForeignKey("Communicator.Server.Domain.Entities.Users.ProfilePicture", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.GroupChats.GcVoiceCall", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.GroupChats.GroupChat", b =>
                {
                    b.Navigation("Icon");

                    b.Navigation("Members");

                    b.Navigation("Messages");

                    b.Navigation("VoiceCalls");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Media.Media", b =>
                {
                    b.Navigation("GroupChatIcon");

                    b.Navigation("MessageAttachments");

                    b.Navigation("ProfilePicture");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Messages.Message", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("DirectMessage");

                    b.Navigation("GroupChatMessage");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Communicator.Server.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("GroupChats");

                    b.Navigation("OwnedMedia");

                    b.Navigation("ProfilePicture");

                    b.Navigation("ReceivedDirectMessages");

                    b.Navigation("SentMessages");

                    b.Navigation("VoiceCalls");
                });
#pragma warning restore 612, 618
        }
    }
}
